contasLuz/contasLuz.Web/Models/ErrorViewModel.cs
using System;

namespace contasLuz.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

contasLuz/contasLuz.Web/Controllers/ContaController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Domain;
using contasLuz.Repositories.Interface;

namespace contasLuz.Web.Controllers
{
    public class ContaController : Controller
    {
        private IContaRepository _repository;

        public ContaController(IContaRepository repository){
        this._repository = repository;
        }

        public IActionResult Index()
        {
            var listConta = _repository.GetAll();
            return View(listConta);
        }
  
        public IActionResult Create()
        {            
            return View();
        }

        [HttpPost]
        public RedirectToActionResult Create(Conta conta)
        {            
            _repository.Create(conta);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {   
            var conta = _repository.GetById(id);
            return View(conta);
        }

        [HttpPost]
        public RedirectToActionResult Edit(Conta conta)
        {            
            _repository.Update(conta);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {   
            _repository.Delete(id);
         return RedirectToAction("Index");
        }
    }
}

contasLuz/contasLuz.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using contasLuz.Web.Models;


namespace contasLuz.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

contasLuz/contasLuz.Web/Views/Conta/Create.cshtml
@model contasLuz.Domain.Entities.Conta

<div class="form-horizontal">
    <form action="Create" method="Post">

           <div class="form-group">
            <label>ID</label>
            <input  class="form-control" readonly
                    type="text" name="id">
        </div>

        <div class="form-group">
            <label>Data Leitura</label>
            <input  class="form-control"
                    type="text" name="dataLeitura"/>
        </div>

        <div class="form-group">
            <label>numero Leitura</label>
            <input  class="form-control"
                    type="text" name="numeroLeitura"/>
        </div>

        <div class="form-group">
            <label>kw Gastos</label>
            <input  class="form-control"
                    type="text" name="kwGasto"/>
        </div>

        <div class="form-group">
            <label>valor Pagar</label>
            <input  class="form-control"
                    type="text" name="valorPagar"/>
        </div>

        <div class="form-group">
            <label>data Pagamento</label>
            <input  class="form-control"
                    type="text" name="dataPagamento"/>
        </div>

        <div class="form-group">
            <label>media Consumo</label>
            <input  class="form-control"
                    type="text" name="mediaConsumo"/>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

contasLuz/contasLuz.Web/Views/Conta/Edit.cshtml
@model contasLuz.Domain.Entities.Conta

<div class="form-horizontal">
    <form action="Edit" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input readonly class="form-control"
                    type="text" name="id" value="@Model.id"/>
        </div>
        
        <div class="form-group">
            <label>Data Leitura</label>
            <input  class="form-control"
                    type="text" name="dataLeitura" value="@Model.dataLeitura"/>
        </div>

        <div class="form-group">
            <label>numero Leitura</label>
            <input readonly class="form-control"
                    type="text" name="numeroLeitura" value="@Model.numeroLeitura"/>
        </div>

        <div class="form-group">
            <label>kw Gastos</label>
            <input  class="form-control"
                    type="text" name="kwGasto" value="@Model.kwGasto"/>
        </div>

        <div class="form-group">
            <label>valor Pagar</label>
            <input  class="form-control"
                    type="text" name="valorPagar" value="@Model.valorPagar"/>
        </div>

        <div class="form-group">
            <label>data Pagamento</label>
            <input  class="form-control"
                    type="text" name="dataPagamento" value="@Model.dataPagamento"/>
        </div>

        <div class="form-group">
            <label>media Consumo</label>
            <input  class="form-control"
                    type="text" name="mediaConsumo" value="@Model.mediaConsumo"/>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

contasLuz/contasLuz.Web/Views/Conta/Index.cshtml
@model IEnumerable<contasLuz.Domain.Entities.Conta>

    

<a href="Conta/Create" class="btn btn-primary">Nova Conta</a>


<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Data Leitura</th>
                <th>Número Leitura</th>
                <th>Kw Gastos</th>
                <th>Valor a Pagar</th>
                <th>Data Pagamento</th>
                <th>Média Consumo</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        @foreach(var item in Model)
        {
            <tr>
                <td>@item.dataLeitura</td>
                <td>@item.numeroLeitura</td>
                <td>@item.kwGasto</td>
                <td>@item.valorPagar</td>
                <td>@item.dataPagamento</td>
                <td>@item.mediaConsumo</td>
                <td><a class="btn btn-danger"
                    href="Conta/Delete/@item.numeroLeitura">Delete</a> </td>
                <td><a class="btn btn-primary" 
                    href="Conta/Edit/@item.id">Editar</a> </td>
            </tr>
        }
    </table>
</div>

contasLuz/contasLuz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - contasLuz</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Conta" asp-action="Index">contasLuz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - contasLuz - <a asp-area="" asp-controller="Conta" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>