contasLuz_Refatorada/contasLuz.MVC/Models/ErrorViewModel.cs
using System;

namespace contasLuz.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

contasLuz_Refatorada/contasLuz.MVC/Controllers/ContaLuzController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using contasLuz.Entities;
using contasLuz.interfaces;
using contasLuz.MVC.Models;
using contasLuz.MVC.ViewsModels;

namespace contasLuz.MVC.Controllers
{
    public class ContaLuzController : Controller
    {
        private readonly IContaLuzRepositories contaLuzRepositories;
        private readonly IImovelRepositories imovelRepositories;

        public ContaLuzController(IContaLuzRepositories contaLuzRepositories, IImovelRepositories imovel)
        {
            this.contaLuzRepositories = contaLuzRepositories;
            this.imovelRepositories = imovel;
        }

        public IActionResult Index()
        {
            ViewBag.imovel= imovelRepositories.GetAll();
            return View(new ContaLuzViewModel(contaLuzRepositories));
        }

        public IActionResult View(int id)
        {
            return View(contaLuzRepositories.Get(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
         //   ViewBag.Topico = new SelectList(db.Topicoes, "Id", "Nome");

            return View();
        }

        [HttpPost]
        public RedirectToActionResult Create(ContaLuz contaLuz)
        {
            contaLuzRepositories.Insert(contaLuz);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            return View(contaLuzRepositories.Get(id));
        }

        [HttpPost]
        public RedirectToActionResult Update(ContaLuz contaLuz)
        {
            contaLuzRepositories.Update(contaLuz);
            return RedirectToAction("Index");
        }

        public RedirectToActionResult Delete(int id)
        {
            contaLuzRepositories.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

contasLuz_Refatorada/contasLuz.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using contasLuz.MVC.Models;

namespace contasLuz.MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

contasLuz_Refatorada/contasLuz.MVC/Controllers/ImovelController.cs
using Microsoft.AspNetCore.Mvc;
using contasLuz.Entities;
using contasLuz.interfaces;


namespace contasLuz.MVC.Controllers
{
    public class ImovelController : Controller
    {
        private IImovelRepositories _Repositories;

        public ImovelController(IImovelRepositories Repositories){
        this._Repositories = Repositories;
        }

        public IActionResult Index()
        {
            var listImoveis = _Repositories.GetAll();
            return View(listImoveis);
        }
  
        public IActionResult Create()
        {            
            return View();
        }

        [HttpPost]
        public RedirectToActionResult Create(Imoveis Imoveis)
        {            
            _Repositories.Create(Imoveis);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {   
            var Imoveis = _Repositories.GetById(id);
            return View(Imoveis);
        }

        [HttpPost]
        public RedirectToActionResult Update(Imoveis Imoveis)
        {            
            _Repositories.Update(Imoveis);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {   
            _Repositories.Delete(id);
         return RedirectToAction("Index");
        }
    }
}

contasLuz_Refatorada/contasLuz.MVC/Views/ContaLuz/Create.cshtml
@model contasLuz.Entities.ContaLuz;
@{
    ViewData["Title"] = "Contas de Luz";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
        
        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Data Leitura
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.dataLeitura, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.dataLeitura)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                KW Gasto
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.kwGasto, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.kwGasto)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Valor a pagar
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.valorAPagar, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.valorAPagar)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Data Pagamento
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.dataPagamento, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.dataPagamento)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Média de Consumo
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.mediaConsumo, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.mediaConsumo)</small>
            </div>
        </div>

        <div class="d-block text-left">
            <button type="submit" class="btn btn-success d-block my-4 text-left">Adicionar</button>

            @Html.ActionLink("Voltar", "Index", null, null, new { @class = "mt-2 d-block" })
        </div>
    
    }

contasLuz_Refatorada/contasLuz.MVC/Views/ContaLuz/Index.cshtml
@model contasLuz.MVC.ViewsModels.ContaLuzViewModel;

@{
    ViewData["Title"] = "Contas de Luz";
}

<h2 class="text-left">Contas de Luz</h2>
<p class="text-left">
    @Html.ActionLink("Adicionar Conta de Luz", "Create", new {}, new { @class = "btn btn-success" })
</p>
<table class="table table-hover table-striped text-center">
    <thead>
        <tr>
            <th>ID</th>
            
            <th>Data Leitura</th>
            <th>KW Gasto</th>
            <th>Valor a pagar</th>
            <th>Data Pagamento</th>
            <th>Média Consumo</th>
            <th>Ações</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.listaContasLuz)
        {
            <tr>
                <th>@item.id</th>
                
                <td>@item.dataLeitura.ToString("dd/MM/yyyy")</td>
                <td>@item.kwGasto</td>
                <td>R$ @item.valorAPagar</td>
                <td>@item.dataPagamento.ToString("dd/MM/yyyy")</td>
                <td>@item.mediaConsumo</td>
                <td class="text-center">
                    <div class="btn-group" role="group" aria-label="actions">
                    <a class="btn btn-secondary" 
                        asp-controller="ContaLuz" 
                        asp-action="Update" 
                        asp-route-id="@item.id"><i class="fas fa-edit"></i></a>

                    <a class="btn btn-secondary" 
                        asp-controller="ContaLuz" 
                        asp-action="Delete" 
                        asp-route-id="@item.id"><i class="fas fa-trash-alt"></i></a>
                        </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<h3 class="my-4">Menor Consumo</h3>
<table class="table table-hover table-striped text-center">
    <thead>
        <tr>
            <th>Data Leitura</th>
            <th>KW Gasto</th>
            <th>Valor a pagar</th>
            <th>Data Pagamento</th>
            <th>Média Consumo</th>
        </tr>
    </thead>

    <tbody>
        @if (Model.listaContasLuz.Any())
        {
        <tr>
            <td>@Model.menorConsumo.dataLeitura.ToString("dd/MM/yyyy")</td>
            <td>@Model.menorConsumo.kwGasto</td>
            <td>R$ @Model.menorConsumo.valorAPagar</td>
            <td>@Model.menorConsumo.dataPagamento.ToString("dd/MM/yyyy")</td>
            <td>@Model.menorConsumo.mediaConsumo</td>
        </tr>
        }
    </tbody>
</table>
<h3 class="my-4">Maior Consumo</h3>
<table class="table table-hover table-striped text-center">
    <thead>
        <tr>
            <th>Data Leitura</th>
            <th>KW Gasto</th>
            <th>Valor a pagar</th>
            <th>Data Pagamento</th>
            <th>Média Consumo</th>
        </tr>
    </thead>

    <tbody>
        @if (Model.listaContasLuz.Any())
        {
        <tr>
            <td>@Model.maiorConsumo.dataLeitura.ToString("dd/MM/yyyy")</td>
            <td>@Model.maiorConsumo.kwGasto</td>
            <td>R$ @Model.maiorConsumo.valorAPagar</td>
            <td>@Model.maiorConsumo.dataPagamento.ToString("dd/MM/yyyy")</td>
            <td>@Model.maiorConsumo.mediaConsumo</td>
        </tr>
        }
    </tbody>
</table>

contasLuz_Refatorada/contasLuz.MVC/Views/ContaLuz/Update.cshtml
@model contasLuz.Entities.ContaLuz;

@{
    ViewData["Title"] = "Contas de Luz";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.id)

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Data Leitura
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.dataLeitura, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.dataLeitura)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                KW Gasto
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.kwGasto, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.kwGasto)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Valor a pagar
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.valorAPagar, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.valorAPagar)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Data Pagamento
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.dataPagamento, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.dataPagamento)</small>
            </div>
        </div>

        <div class="form-group col-12 col-sm-8 col-md-6 text-left">
            <div class="editor-label">
                Média de Consumo
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.mediaConsumo, new { htmlAttributes = new { @class = "form-control"} })
                <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.mediaConsumo)</small>
            </div>
        </div>

        <div class="d-block text-left">
            <button type="submit" class="btn btn-success d-block my-4 text-left">Atualizar</button>

            @Html.ActionLink("Voltar", "Index", null, null, new { @class = "mt-2 d-block" })
        </div>
    }

contasLuz_Refatorada/contasLuz.MVC/Views/ContaLuz/View.cshtml
@model contasLuz.Entities.ContaLuz;

@{
    ViewData["Title"] = "Contas de Luz";
}

<h2 class="text-center">Contas de Luz</h2>

<div class="form-group col-12 col-sm-8 col-md-6 mx-auto">
    <div class="editor-label">
        Data Leitura
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.dataLeitura, new { htmlAttributes = new { @class = "form-control", @disabled = "true"} })
        <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.dataLeitura)</small>
    </div>
</div>

<div class="form-group col-12 col-sm-8 col-md-6 mx-auto">
    <div class="editor-label">
        KW Gasto
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.kwGasto, new { htmlAttributes = new { @class = "form-control", @disabled = "true"} })
        <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.kwGasto)</small>
    </div>
</div>

<div class="form-group col-12 col-sm-8 col-md-6 mx-auto">
    <div class="editor-label">
        Valor a pagar
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.valorAPagar, new { htmlAttributes = new { @class = "form-control", @disabled = "true"} })
        <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.valorAPagar)</small>
    </div>
</div>

<div class="form-group col-12 col-sm-8 col-md-6 mx-auto">
    <div class="editor-label">
        Data Pagamento
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.dataPagamento, new { htmlAttributes = new { @class = "form-control", @disabled = "true"} })
        <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.dataPagamento)</small>
    </div>
</div>

<div class="form-group col-12 col-sm-8 col-md-6 mx-auto">
    <div class="editor-label">
        Média de Consumo
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.mediaConsumo, new { htmlAttributes = new { @class = "form-control", @disabled = "true"} })
        <small class="form-text text-muted">@Html.ValidationMessageFor(model => model.mediaConsumo)</small>
    </div>
</div>

<div class="d-block text-center">
    @Html.ActionLink("Voltar para listagem", "Index", null, null, new { @class = "mt-4 btn btn-info" })
</div>

contasLuz_Refatorada/contasLuz.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

contasLuz_Refatorada/contasLuz.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - contasLuz.MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">contasLuz.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContaLuz" asp-action="Index">Conta Luz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imovel" asp-action="Index">Imoveis</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - contasLuz.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>